export const MOCK_PRODUCTS = [
  {
    id: "1",
    name: "Texapon N70 (SLES)",
    slug: "texapon-n70",
    description: "Le Texapon N70 est un tensioactif anionique très utilisé dans la fabrication de détergents liquides, de shampoings et de savons liquides. Il offre d'excellentes propriétés moussantes et détergentes.",
    short_desc: "Tensioactif très moussant pour savons et détergents.",
    price: 3500,
    stock: 250,
    unit: "kg",
    category: "Bases Lavantes",
    images: ["https://images.unsplash.com/photo-1611079830811-865ff4428d17?q=80&w=1000&auto=format&fit=crop"],
    is_active: true,
  },
  {
    id: "2",
    name: "Comperlan KD",
    slug: "comperlan-kd",
    description: "Épaississant et stabilisateur de mousse idéal pour les préparations cosmétiques et les détergents.",
    short_desc: "Épaississant et stabilisateur de mousse.",
    price: 4200,
    stock: 120,
    unit: "kg",
    category: "Épaississants",
    images: ["https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?q=80&w=1000&auto=format&fit=crop"],
    is_active: true,
  },
  {
    id: "3",
    name: "Acide Sulfonique",
    slug: "acide-sulfonique",
    description: "Matière première de base pour la fabrication de détergents liquides et en poudre. Fort pouvoir dégraissant.",
    short_desc: "Base détergente à fort pouvoir dégraissant.",
    price: 2800,
    stock: 0,
    unit: "litre",
    category: "Bases Lavantes",
    images: ["https://images.unsplash.com/photo-1584346133934-a3afd2a33c4c?q=80&w=1000&auto=format&fit=crop"],
    is_active: true,
  },
  {
    id: "4",
    name: "Fragrance (Parfum Citron)",
    slug: "fragrance-citron",
    description: "Fragrance concentrée de citron pour détergents et nettoyants multi-surfaces.",
    short_desc: "Fragrance concentrée de citron.",
    price: 15000,
    stock: 20,
    unit: "litre",
    category: "Parfums",
    images: ["https://images.unsplash.com/photo-1596755490729-37bd51c144bb?q=80&w=1000&auto=format&fit=crop"],
    is_active: true,
  },
  {
    id: "5",
    name: "Pasta",
    slug: "pasta",
    description: "Matière première essentielle pour la fabrication de détergents.",
    short_desc: "Idéal pour les détergents.",
    price: 3000,
    stock: 100,
    unit: "kg",
    category: "Bases Lavantes",
    images: ["https://images.unsplash.com/photo-1611079830811-865ff4428d17?q=80&w=1000&auto=format&fit=crop"],
    is_active: true,
  },
  {
    id: "6",
    name: "Nonil Fenol",
    slug: "nonil-fenol",
    description: "Tensioactif non ionique utilisé dans diverses formulations chimiques.",
    short_desc: "Tensioactif non ionique.",
    price: 4500,
    stock: 50,
    unit: "litre",
    category: "Tensioactifs",
    images: ["https://images.unsplash.com/photo-1584346133934-a3afd2a33c4c?q=80&w=1000&auto=format&fit=crop"],
    is_active: true,
  },
  {
    id: "7",
    name: "Glycérine",
    slug: "glycerine",
    description: "Agent hydratant très utilisé dans les produits cosmétiques et savons.",
    short_desc: "Agent hydratant cosmétique.",
    price: 2500,
    stock: 200,
    unit: "litre",
    category: "Bases Lavantes",
    images: ["https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?q=80&w=1000&auto=format&fit=crop"],
    is_active: true,
  },
  {
    id: "8",
    name: "Amonio",
    slug: "amonio",
    description: "Composé chimique utilisé pour les produits d'entretien ménager.",
    short_desc: "Pour produits d'entretien.",
    price: 1800,
    stock: 120,
    unit: "litre",
    category: "Conservateurs",
    images: ["https://images.unsplash.com/photo-1585644158404-3677b10c660f?q=80&w=1000&auto=format&fit=crop"],
    is_active: true,
  },
  {
    id: "9",
    name: "Acetona",
    slug: "acetona",
    description: "Solvant puissant pour diverses applications industrielles.",
    short_desc: "Solvant industriel.",
    price: 3200,
    stock: 60,
    unit: "litre",
    category: "Bases Lavantes",
    images: ["https://images.unsplash.com/photo-1610364841687-393282eb1102?q=80&w=1000&auto=format&fit=crop"],
    is_active: true,
  },
  {
    id: "10",
    name: "Plantarin",
    slug: "plantarin",
    description: "Tensioactif doux d'origine végétale pour cosmétiques naturels.",
    short_desc: "Tensioactif végétal doux.",
    price: 5500,
    stock: 40,
    unit: "kg",
    category: "Tensioactifs",
    images: ["https://images.unsplash.com/photo-1584346133934-a3afd2a33c4c?q=80&w=1000&auto=format&fit=crop"],
    is_active: true,
  },
  {
    id: "11",
    name: "Betaina",
    slug: "betaina",
    description: "Tensioactif amphotère très doux, idéal pour les shampoings.",
    short_desc: "Tensioactif doux pour shampoings.",
    price: 4800,
    stock: 75,
    unit: "kg",
    category: "Tensioactifs",
    images: ["https://images.unsplash.com/photo-1611079830811-865ff4428d17?q=80&w=1000&auto=format&fit=crop"],
    is_active: true,
  }
];

export const MOCK_TRAININGS = [
  {
    id: "t1",
    title: "Fabrication de Savon Liquide et Détergent",
    slug: "savon-liquide",
    description: "Apprenez les techniques professionnelles pour fabriquer du savon liquide et des détergents de haute qualité de A à Z.",
    full_description: "Cette formation de 3 jours couvre toutes les étapes de la fabrication de détergents liquides. Vous apprendrez à manipuler les matières premières (Texapon, Acide Sulfonique), à équilibrer le pH, et à créer des formules stables et performantes.",
    objectives: [
      "Comprendre les différents types de tensioactifs",
      "Formuler un savon liquide multi-usages",
      "Mesurer et ajuster le pH",
      "Techniques de conservation et d'ajout de parfum"
    ],
    date_start: "2026-06-15",
    date_end: "2026-06-17",
    location: "Centre de formation NCP, Pétion-Ville, Haïti",
    max_seats: 20,
    current_seats: 5,
    price: 75000,
    image: "https://images.unsplash.com/photo-1585644158404-3677b10c660f?q=80&w=1000&auto=format&fit=crop",
    is_active: true,
  },
  {
    id: "t2",
    title: "Cosmétique Naturelle : Lait de corps",
    slug: "cosmetique-lait-corps",
    description: "Formation pratique sur la formulation et la fabrication de laits corporels hydratants et éclaircissants.",
    full_description: "Découvrez les secrets de l'émulsion pour créer des crèmes et laits corporels de qualité professionnelle. Une formation 100% pratique encadrée par des chimistes expérimentés.",
    objectives: [
      "Maîtriser les émulsions eau dans huile et huile dans eau",
      "Choix des conservateurs adaptés",
      "Incorporation d'actifs naturels",
    ],
    date_start: "2026-07-05",
    date_end: "2026-07-06",
    location: "Centre de formation NCP, Pétion-Ville, Haïti",
    max_seats: 15,
    current_seats: 15, // Complet
    price: 50000,
    image: "https://images.unsplash.com/photo-1611079830811-865ff4428d17?q=80&w=1000&auto=format&fit=crop",
    is_active: true,
  }
];

export const CATEGORIES = [
  "Tous",
  "Bases Lavantes",
  "Tensioactifs",
  "Parfums",
  "Épaississants",
  "Conservateurs",
  "Colorants"
];
